project:
  type: website
  output-dir: docs

website:
  title: "My example website"
  navbar:
    left:
      - href: index.qmd
        text: Homepage
      - about.qmd
      
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Assignments"
        contents:
          - href: ae03-gerrymander.qmd
           
format:
  html:
    theme:
      - slate
      - brand
    css: styles.css
    toc: true



